### ISSUE TITLE
Suggestions for adjustments

### ISSUE THREAD

**Issue by tatyanepgoncalves** [allesonsales/advice-generator#1]
Hello Alleson, how are you?
First of all, I would like to congratulate you on the challenge you accomplished. It was great.

To improve the project so that it doesn't have a scroll bar in the version for larger screens, I suggest the following changes:

In **index.html**:
Place the `attribution` class inside the `main` tag. Like this:
```html
<main>
<div class="container">
<div class="advice-top">
<div class="advice-id">
<span>Advice #117</span>
</div>
<div class="advice-text">
"It is easy to sit up and take notice,
What's difficult is getting up and taking action." </div>
 </div>
 <div class="advice-wrapper">
 </div>
 <div class="advice-button" id="button">
 <img src="https://raw.githubusercontent.com/allesonsales/advice-generator/43f05256c9d462ea3df637f52527282fdea09948/images/icon-dice.svg" alt="Generate new Advice">
 </div>
 </div>

 <div class="attribution">
 Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>.
 Coded by <a href="https://www.frontendmentor.io/profile/allesonsales">Alleson Sales</a>.
 </div>
</main>
```

In **style.css**:
1- Add rotate to the icon of the `advice-button` class.
```css

.advice-button:hover img {
 transform: rotate(45deg);
}
```

2 - Add to the `attribution` class.
```css
.attribution {
 position: fixed;
 bottom: 1rem;
 font-size: 11px;
 text-align: center;
 margin: 1rem;
 color: var(--Neon-Green);
}
```

Again, congratulations on the project!
